In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("students.csv")
print("------------------------------------------------------------------")
print(df.shape)
print("------------------------------------------------------------------")
print(df.info())

------------------------------------------------------------------
(20, 7)
------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_ID          20 non-null     int64
 1   Name                20 non-null     str
 2   Department          20 non-null     str
 3   Python_Marks        20 non-null     int64
 4   AI_Marks            20 non-null     int64
 5   Maths_Marks         20 non-null     int64
 6   Attendance_Percent  20 non-null     int64
dtypes: int64(5), str(2)
memory usage: 1.0 KB
None

In [3]:
display(df.head())
print("-----------------------------------------------------------")
display(df.tail())

,Student_ID,Name,Department,Python_Marks,AI_Marks,Maths_Marks,Attendance_Percent
0,101,Aarav Patil,AIML,86,91,88,92
1,102,Ananya Shah,AIML,78,84,81,95
2,103,Rohan Deshmukh,CSE,67,73,70,82
3,104,Sneha Kulkarni,AIML,94,89,96,98
4,105,Om Jadhav,CSE,52,61,58,68

-----------------------------------------------------------

,Student_ID,Name,Department,Python_Marks,AI_Marks,Maths_Marks,Attendance_Percent
15,116,Aditi Salunkhe,AIML,97,94,98,99
16,117,Neel Pawar,CSE,74,68,72,80
17,118,Riya Khot,AIML,62,70,66,85
18,119,Parth Gawade,CSE,89,82,86,88
19,120,Tanvi Nikam,AIML,56,63,60,90

In [4]:
df["Total_Marks"] = df["Python_Marks"] + df["AI_Marks"] + df["Maths_Marks"]
df["Average_Marks"] = df["Total_Marks"] / 3
print(df[["Name", "Total_Marks", "Average_Marks"]])
df.head()
#Calculate total marks and average marks for each student.

              Name  Total_Marks  Average_Marks
0      Aarav Patil          265      88.333333
1      Ananya Shah          243      81.000000
2   Rohan Deshmukh          210      70.000000
3   Sneha Kulkarni          279      93.000000
4        Om Jadhav          171      57.000000
5        Isha More          271      90.333333
6     Vedant Joshi          142      47.333333
7      Priya Pawar          228      76.000000
8     Sahil Chavan          242      80.666667
9      Meera Kadam          279      93.000000
10    Atharva Mane          146      48.666667
11      Diya Sutar          214      71.333333
12   Kunal Bhosale          184      61.333333
13    Sana Inamdar          255      85.000000
14     Yash Shinde          111      37.000000
15  Aditi Salunkhe          289      96.333333
16      Neel Pawar          214      71.333333
17       Riya Khot          198      66.000000
18    Parth Gawade          257      85.666667
19     Tanvi Nikam          179      59.666667

,Student_ID,Name,Department,Python_Marks,AI_Marks,Maths_Marks,Attendance_Percent,Total_Marks,Average_Marks
0,101,Aarav Patil,AIML,86,91,88,92,265,88.333333
1,102,Ananya Shah,AIML,78,84,81,95,243,81.000000
2,103,Rohan Deshmukh,CSE,67,73,70,82,210,70.000000
3,104,Sneha Kulkarni,AIML,94,89,96,98,279,93.000000
4,105,Om Jadhav,CSE,52,61,58,68,171,57.000000

In [5]:

print("Highest Average:", df["Average_Marks"].max())
print("Lowest Average:", df["Average_Marks"].min())
print("Class Average:", df["Average_Marks"].mean())

Highest Average: 96.33333333333333
Lowest Average: 37.0
Class Average: 72.95

In [6]:
def grade(Marks):
    if(Marks)>90:
        return 'A'
    elif(Marks)>70:
        return 'B'
    elif(Marks)>50:
        return 'C'
    else:
        return 'F'   

#Assign grades based on a clearly defined grading rule.  reusable functions

In [7]:
df["Grade"] = df["Average_Marks"].apply(grade)
print(df[["Student_ID","Average_Marks","Grade"]])
#Assign grades based on a clearly defined grading rule.

    Student_ID  Average_Marks Grade
0          101      88.333333     B
1          102      81.000000     B
2          103      70.000000     C
3          104      93.000000     A
4          105      57.000000     C
5          106      90.333333     A
6          107      47.333333     F
7          108      76.000000     B
8          109      80.666667     B
9          110      93.000000     A
10         111      48.666667     F
11         112      71.333333     B
12         113      61.333333     C
13         114      85.000000     B
14         115      37.000000     F
15         116      96.333333     A
16         117      71.333333     B
17         118      66.000000     C
18         119      85.666667     B
19         120      59.666667     C

In [8]:
def check(Grade):
    if(Grade)=='F':
        return "Fail"
    else:
        return "Pass"

 #Identify pass/fail students using a clearly defined condition. reusable functions

In [9]:
df["Result"] = df["Grade"].apply(check)
print(df[["Student_ID","Average_Marks","Grade","Result"]])

    Student_ID  Average_Marks Grade Result
0          101      88.333333     B   Pass
1          102      81.000000     B   Pass
2          103      70.000000     C   Pass
3          104      93.000000     A   Pass
4          105      57.000000     C   Pass
5          106      90.333333     A   Pass
6          107      47.333333     F   Fail
7          108      76.000000     B   Pass
8          109      80.666667     B   Pass
9          110      93.000000     A   Pass
10         111      48.666667     F   Fail
11         112      71.333333     B   Pass
12         113      61.333333     C   Pass
13         114      85.000000     B   Pass
14         115      37.000000     F   Fail
15         116      96.333333     A   Pass
16         117      71.333333     B   Pass
17         118      66.000000     C   Pass
18         119      85.666667     B   Pass
19         120      59.666667     C   Pass

In [10]:
count_pass = (df["Result"]=='Pass').sum()
count_fail = (df["Result"]=='Fail').sum()
print("Passed students-",count_pass)
print("Failed students-",count_fail)
# Identify pass/fail students using a clearly defined condition.

Passed students- 17
Failed students- 3

In [11]:
Total = count_pass + count_fail
pass_percentage = (count_pass/Total)*100
fail_percentage = (count_fail/Total)*100
print("Pass percentage(%)-",pass_percentage)
print("Fail percentage(%)-",fail_percentage)
# Identify pass/fail students using a clearly defined condition.

Pass percentage(%)- 85.0
Fail percentage(%)- 15.0

In [12]:
Python_Average = df["Python_Marks"].mean()
AI_Average = df["AI_Marks"].mean()
Maths_Average = df["Maths_Marks"].mean()
print("Python_Average-",Python_Average)
print("AI_Average-",AI_Average)
print("Maths_Average-",Maths_Average)
#Generate subject-wise performance analysis.

Python_Average- 70.6
AI_Average- 74.5
Maths_Average- 73.75

In [13]:
def getmax(m1,m2,m3):
    return np.max([m1,m2,m3])
def getmin(m1,m2,m3):
    return np.min([m1,m2,m3])

highest_avg = getmax(Python_Average,AI_Average,Maths_Average)
lowest_avg = getmin(Python_Average,AI_Average,Maths_Average)

print("Highest_avg-",highest_avg)
print("Lowest_avg-",lowest_avg)

Highest_avg- 74.5
Lowest_avg- 70.6

In [14]:
Python_max = df["Python_Marks"].max()
AI_max = df["AI_Marks"].max()
Maths_max = df["Maths_Marks"].max()
Python_min = df["Python_Marks"].min()
AI_min = df["AI_Marks"].min()
Maths_min = df["Maths_Marks"].min()

print("Python Highest Marks, Python Lowest Marks = ",Python_max,Python_min)
print("AI Highest Marks, AI Lowest Marks = ",AI_max,AI_min)
print("Maths Highest Marks, Maths Lowest Marks = ",Maths_max,Maths_min)


# Find highest, lowest and average performance.

Python Highest Marks, Python Lowest Marks =  97 31
AI Highest Marks, AI Lowest Marks =  95 42
Maths Highest Marks, Maths Lowest Marks =  98 38

In [15]:
Python_Topper = df.loc[df["Python_Marks"] == Python_max, "Name"]
AI_Topper = df.loc[df["AI_Marks"] == AI_max, "Name"]
Maths_Topper = df.loc[df["Maths_Marks"] == Maths_max, "Name"]

print("Python Topper-",Python_Topper)
print("AI Topper-",AI_Topper)
print("Maths Topper-",Maths_Topper)
#Generate subject-wise performance analysis.

Python Topper- 15    Aditi Salunkhe
Name: Name, dtype: str
AI Topper- 9    Meera Kadam
Name: Name, dtype: str
Maths Topper- 15    Aditi Salunkhe
Name: Name, dtype: str

In [16]:
Class_Topper = df.loc[df["Average_Marks"].max() == df["Average_Marks"], "Name"]

print("Class Topper-", Class_Topper)

#Identify top-performing students.

Class Topper- 15    Aditi Salunkhe
Name: Name, dtype: str

In [17]:
Avg_Attendance = df["Attendance_Percent"].mean()
print("Avg_Attendance-",Avg_Attendance)
print("-------------------------------------------------------------------------")
print("is_Attendance_Defaulter")
df["Attendance_defaulter"] = df["Attendance_Percent"] <= 75
print(df[["Name","Attendance_defaulter"]])

Avg_Attendance- 83.65
-------------------------------------------------------------------------
is_Attendance_Defaulter
              Name  Attendance_defaulter
0      Aarav Patil                 False
1      Ananya Shah                 False
2   Rohan Deshmukh                 False
3   Sneha Kulkarni                 False
4        Om Jadhav                  True
5        Isha More                 False
6     Vedant Joshi                  True
7      Priya Pawar                 False
8     Sahil Chavan                 False
9      Meera Kadam                 False
10    Atharva Mane                  True
11      Diya Sutar                 False
12   Kunal Bhosale                  True
13    Sana Inamdar                 False
14     Yash Shinde                  True
15  Aditi Salunkhe                 False
16      Neel Pawar                 False
17       Riya Khot                 False
18    Parth Gawade                 False
19     Tanvi Nikam                 False

In [18]:
AIML_maxavgMark = df[df["Department"] == 'AIML']["Average_Marks"].max()
CSE_maxavgMark = df[df["Department"] == 'CSE']["Average_Marks"].max()
print("AIML maximum average marks-",AIML_maxavgMark)
print("CSE maximum average marks-",CSE_maxavgMark)

AIML maximum average marks- 96.33333333333333
CSE maximum average marks- 85.66666666666667